

const PROGRESS_KEY='iqraEnterpriseProgressV11';
let soundEnabled=localStorage.getItem('iqraSoundEnabled')!=='false';
let progressState={percent:0,completed:[]};
try{const savedProgress=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');if(savedProgress)progressState={...progressState,...savedProgress}}catch(e){}
function saveProgress(){localStorage.setItem(PROGRESS_KEY,JSON.stringify(progressState))}
function openRestartModal(){document.getElementById('restartModal')?.classList.add('show')}
function closeRestartModal(){document.getElementById('restartModal')?.classList.remove('show')}
function confirmRestartJourney(){
  progressState={percent:0,completed:[]};
  localStorage.removeItem(PROGRESS_KEY);
  localStorage.removeItem('iqraCertificate');
  localStorage.removeItem('iqraLetterMastery');
  localStorage.removeItem('iqraGameScores');
  localStorage.removeItem(GAME_KEY); gameState={stars:0,completed:[],bestHunt:0,bestBalloon:0}; renderGameStats();
  const st=document.getElementById('stars');if(st)st.textContent='0';
  saveProgress();renderProgress();closeRestartModal();showTab('child');
  showGuide('بدأت رحلة جديدة. هيا نضيء المحطة الأولى!');sparkles();
}
function resetJourney(){openRestartModal()}
function startJourney(){
  if((Number(progressState.percent)||0)>=100){openRestartModal();return}
  showTab('quran');
  if((Number(progressState.percent)||0)===0){setProgress(5,0,'بدأت رحلتك، بارك الله فيك!')}
}
function renderProgress(){
  const pct=Math.max(0,Math.min(100,Number(progressState.percent)||0));
  const b=document.getElementById('mainBar'),v=document.getElementById('progressPercent'),f=document.getElementById('journeyFill');
  if(b)b.style.width=pct+'%';if(v)v.textContent=pct;if(f)f.style.width=(pct*.86)+'%';
  document.querySelectorAll('.station').forEach((el,i)=>{el.classList.toggle('done',progressState.completed.includes(i));el.classList.toggle('current',!progressState.completed.includes(i)&&i===Math.min(5,Math.floor(pct/20)))})
}
function setProgress(percent,step,message){const old=progressState.percent;progressState.percent=Math.max(progressState.percent,percent);if(step!=null&&!progressState.completed.includes(step))progressState.completed.push(step);saveProgress();renderProgress();if(progressState.percent>old){showGuide(message||'أضاء نجمك أكثر!');sparkles();successSound()}}
function toggleSound(){soundEnabled=!soundEnabled;localStorage.setItem('iqraSoundEnabled',soundEnabled);renderSoundToggle();if(soundEnabled){successSound();showGuide('تم تشغيل الأصوات التشجيعية.')}}
function renderSoundToggle(){const b=document.getElementById('soundToggle');if(b)b.innerHTML=soundEnabled?'🔊 الأصوات':'🔇 الأصوات'}
function tone(freq,duration=.13,delay=0){if(!soundEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext;const ctx=window.__iqraAudioCtx||(window.__iqraAudioCtx=new C());const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.001,ctx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.11,ctx.currentTime+delay+.02);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+duration);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+delay);o.stop(ctx.currentTime+delay+duration+.03)}catch(e){}}
function successSound(){tone(523,.12,0);tone(659,.12,.11);tone(784,.19,.22)}
function gentleTrySound(){tone(392,.10,0);tone(440,.14,.12)}
let guideTimer;
function showGuide(text,ms=3600){const g=document.getElementById('starGuide'),b=document.getElementById('guideBubble');if(!g||!b)return;b.textContent=text;g.classList.add('show');clearTimeout(guideTimer);guideTimer=setTimeout(()=>g.classList.remove('show'),ms)}
function sparkles(){for(let i=0;i<9;i++){const e=document.createElement('span');e.className='spark';e.textContent=i%2?'✦':'★';e.style.left=(35+Math.random()*80)+'px';e.style.bottom=(35+Math.random()*35)+'px';e.style.setProperty('--dx',(Math.random()*100-50)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),1300)}}
function encourage(text,kind='success'){showGuide(text);if(kind==='success')successSound();else gentleTrySound()}
renderProgress();renderSoundToggle();setTimeout(()=>showGuide('أهلًا بك في رحلة اقرأ وتعلّم. هيا نضيء أولى المحطات!'),700);

const sections=[...document.querySelectorAll('.section')]; const tabBtns=[...document.querySelectorAll('.tabs button')];
function showTab(id){sections.forEach(s=>s.classList.remove('active')); document.getElementById(id)?.classList.add('active'); tabBtns.forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); window.scrollTo({top:0,behavior:'smooth'});} tabBtns.forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
const plan=['آية 1–2','آية 3','آية 4–5','آية 6','آية 7–8','آية 9 + مراجعة','آية 10','آية 11–12','آية 13 + مراجعة','آية 14','آية 15','آية 16 + مراجعة','آية 17','آية 18','آية 19 + مراجعة'];
document.getElementById('ayahPlan').innerHTML=plan.map((p,i)=>`<div class="item"><span>اليوم ${i+1}: ${p}</span><span class="badge">${i<3?'مفتوح':'قريبًا'}</span></div>`).join('');
const letterData=[
['ا','ألف'],['ب','باء'],['ت','تاء'],['ث','ثاء'],['ج','جيم'],['ح','حاء'],['خ','خاء'],['د','دال'],['ذ','ذال'],['ر','راء'],['ز','زاي'],['س','سين'],['ش','شين'],['ص','صاد'],['ض','ضاد'],['ط','طاء'],['ظ','ظاء'],['ع','عين'],['غ','غين'],['ف','فاء'],['ق','قاف'],['ك','كاف'],['ل','لام'],['م','ميم'],['ن','نون'],['هـ','هاء'],['و','واو'],['ي','ياء']];
const letters=letterData.map(x=>x[0]);let selectedLetterIndex=0;
const letterStages=[[0,5],[5,10],[10,15],[15,20],[20,28]];
const videoSegments={
'ا':[0.0,3.85],'ب':[3.85,7.7],'ت':[7.7,11.55],'ث':[11.55,15.4],'ج':[15.4,19.25],'ح':[19.25,23.1],'خ':[23.1,26.95],
'د':[26.95,30.8],'ذ':[30.8,34.65],'ر':[34.65,38.5],'ز':[38.5,42.35],'س':[42.35,46.2],'ش':[46.2,50.9]};
let currentStage=0,videoStopTimer=null;
let masteredLetters=new Set(JSON.parse(localStorage.getItem('iqraMasteredLetters')||'[]'));
function getLetterName(ch){return (letterData.find(x=>x[0]===ch)||[ch,ch])[1]}
function speakText(txt){if(!soundEnabled)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.lang='ar-SA';u.rate=.62;u.pitch=1;u.volume=1;speechSynthesis.speak(u)}catch(e){}}
function say(txt){speakText(txt)}
function renderStageNav(){letterStageNav.innerHTML=letterStages.map((s,i)=>`<button class="stage-btn ${i===currentStage?'active':''}" onclick="setLetterStage(${i})">المرحلة ${i+1}</button>`).join('')}
function setLetterStage(i){currentStage=i;const [a,b]=letterStages[i];if(selectedLetterIndex<a||selectedLetterIndex>=b)selectedLetterIndex=a;renderStageNav();renderLetterList();selectLetter(selectedLetterIndex,false)}
function renderLetterList(){const [a,b]=letterStages[currentStage];letterList.innerHTML=letterData.slice(a,b).map((x,j)=>{const i=a+j,state=masteredLetters.has(x[0])?'mastered':(i===selectedLetterIndex?'learning':'');return `<button class="letter ${i===selectedLetterIndex?'active':''} ${state}" onclick="selectLetter(${i})" aria-label="${x[1]}">${x[0]}</button>`}).join('');lettersMasteredText.textContent=masteredLetters.size+' من 28 حرفًا متقنًا'}
function selectLetter(i,autoPlay=true){selectedLetterIndex=i;const st=letterStages.findIndex(([a,b])=>i>=a&&i<b);if(st!==currentStage){currentStage=st;renderStageNav()}renderLetterList();const [ch,name]=letterData[i];selectedLetterName.textContent=name;videoLetterLabel.textContent='النطق المرجعي: '+name;letterStateBadge.textContent=masteredLetters.has(ch)?'متقن':'قيد التعلم';drawTraceGuide();clearFreeWriting();if(autoPlay)speakSelectedLetter()}
function playSelectedVideoSegment(){const [ch,name]=letterData[selectedLetterIndex],seg=videoSegments[ch];clearTimeout(videoStopTimer);if(!seg){videoSourceNote.textContent='الفيديو المرفق يتضمن الحروف حتى الشين؛ سيُستخدم النطق العربي المدمج لهذا الحرف.';speakText(name);return}videoSourceNote.textContent='تشغيل النطق الصحيح من الفيديو التعليمي المرفق.';lettersVideo.currentTime=seg[0];lettersVideo.play().then(()=>{videoStopTimer=setTimeout(()=>lettersVideo.pause(),Math.max(500,(seg[1]-seg[0])*1000))}).catch(()=>{});lettersVideo.ontimeupdate=()=>{if(lettersVideo.currentTime>=seg[1]){lettersVideo.pause();lettersVideo.ontimeupdate=null}}}
function speakSelectedLetter(){playSelectedVideoSegment()}
function nextLetter(){selectLetter((selectedLetterIndex+1)%letterData.length);clearTrace()}
const traceCanvas=document.getElementById('traceCanvas'),tctx=traceCanvas.getContext('2d'),freeCanvas=document.getElementById('freeCanvas'),fctx=freeCanvas.getContext('2d');let drawing=false,tracePoints=0,freeDrawing=false,freePoints=0;
function fitOneCanvas(canvas,ctx){const dpr=Math.max(1,window.devicePixelRatio||1),rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.width*.75*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function fitTraceCanvas(){fitOneCanvas(traceCanvas,tctx);fitOneCanvas(freeCanvas,fctx);drawTraceGuide();clearFreeWriting()}
function drawTraceGuide(){const w=traceCanvas.clientWidth||560,h=(traceCanvas.clientWidth||560)*.75;tctx.clearRect(0,0,w,h);tctx.save();tctx.textAlign='center';tctx.textBaseline='middle';tctx.font=`900 ${Math.min(w*.42,h*.55)}px Tahoma,Arial`;tctx.setLineDash([10,10]);tctx.lineWidth=4;tctx.strokeStyle='#aebfc0';const ch=letterData[selectedLetterIndex][0];tctx.strokeText(ch,w*.25,h*.5);tctx.strokeText(ch,w*.5,h*.5);tctx.strokeText(ch,w*.75,h*.5);tctx.fillStyle='rgba(11,107,120,.025)';tctx.fillText(ch,w*.25,h*.5);tctx.fillText(ch,w*.5,h*.5);tctx.fillText(ch,w*.75,h*.5);tctx.restore();tracePoints=0;traceMsg.textContent=''}
function clearFreeWriting(){const w=freeCanvas.clientWidth||560,h=(freeCanvas.clientWidth||560)*.75;fctx.clearRect(0,0,w,h);fctx.save();fctx.setLineDash([5,8]);fctx.strokeStyle='#d8e4e4';fctx.lineWidth=2;fctx.beginPath();fctx.moveTo(20,h*.72);fctx.lineTo(w-20,h*.72);fctx.stroke();fctx.restore();freePoints=0}
function pos(canvas,e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function bindDrawing(canvas,ctx,isFree){let active=false;const down=e=>{e.preventDefault();active=true;const p=pos(canvas,e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!active)return;e.preventDefault();const p=pos(canvas,e);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=isFree?'#d8a437':'#0b6b78';ctx.lineWidth=isFree?14:16;ctx.lineTo(p.x,p.y);ctx.stroke();if(isFree)freePoints++;else tracePoints++};const up=()=>active=false;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',up);canvas.addEventListener('touchstart',down,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',up)}
bindDrawing(traceCanvas,tctx,false);bindDrawing(freeCanvas,fctx,true);
function clearTrace(){drawTraceGuide()}
function checkTrace(){const ch=letterData[selectedLetterIndex][0];if(tracePoints>25&&freePoints>12){masteredLetters.add(ch);localStorage.setItem('iqraMasteredLetters',JSON.stringify([...masteredLetters]));traceMsg.textContent='أحسنت! تتبعت الحرف وكتبته بنفسك ⭐';traceMsg.style.color='var(--green)';letterStateBadge.textContent='متقن';renderLetterList();setProgress(Math.min(64,45+Math.round(masteredLetters.size/28*19)),1,'أحسنت! أتقنت حرفًا جديدًا.');successSound();sparkles()}else if(tracePoints<=25){traceMsg.textContent='تتبّع الحروف المنقّطة كاملة أولًا.';traceMsg.style.color='#a56a00';gentleTrySound()}else{traceMsg.textContent='اكتب الحرف مرة واحدة في المساحة الحرة ثم أعد التحقق.';traceMsg.style.color='#a56a00';gentleTrySound()}}
renderStageNav();renderLetterList();setTimeout(()=>{fitTraceCanvas();selectLetter(0,false)},100);window.addEventListener('resize',fitTraceCanvas);

let huntTarget='ب',huntTimer=null,huntSpawn=null,huntRemaining=30,huntScoreValue=0,huntRunning=false;
function repeatGameSound(){const i=letters.indexOf(huntTarget);if(i>=0){const old=selectedLetterIndex;selectedLetterIndex=i;playSelectedVideoSegment();selectedLetterIndex=old}else speakText(getLetterName(huntTarget))}
function startLetterHunt(){stopLetterHunt();huntRunning=true;huntRemaining=30;huntScoreValue=0;huntScore.textContent='0';huntTime.textContent='30';fallingLetters.innerHTML='';chooseHuntTarget();huntTimer=setInterval(()=>{huntRemaining--;huntTime.textContent=huntRemaining;if(huntRemaining<=0)finishLetterHunt()},1000);huntSpawn=setInterval(spawnFallingLetter,850);for(let i=0;i<4;i++)setTimeout(spawnFallingLetter,i*180)}
function chooseHuntTarget(){huntTarget=letters[Math.floor(Math.random()*letters.length)];gamePrompt.textContent='التقط حرف «'+huntTarget+'» — '+getLetterName(huntTarget);speakText(getLetterName(huntTarget))}
function spawnFallingLetter(){if(!huntRunning)return;const el=document.createElement('button');const isTarget=Math.random()<.32;const ch=isTarget?huntTarget:letters[Math.floor(Math.random()*letters.length)];el.className='falling-letter';el.textContent=ch;el.style.right=(4+Math.random()*84)+'%';el.style.animationDuration=(3.2+Math.random()*2.5)+'s';el.onclick=()=>hitFallingLetter(el,ch);el.addEventListener('animationend',()=>el.remove());fallingLetters.appendChild(el)}
function hitFallingLetter(el,ch){if(!huntRunning)return;if(ch===huntTarget){huntScoreValue+=10;huntScore.textContent=huntScoreValue;el.classList.add('correct-pop');gameMsg.textContent='أحسنت! التقطت الحرف الصحيح ⭐';successSound();sparkles();setTimeout(()=>el.remove(),350);if(huntScoreValue%30===0)chooseHuntTarget()}else{huntScoreValue=Math.max(0,huntScoreValue-2);huntScore.textContent=huntScoreValue;el.classList.add('bad');gameMsg.textContent='هذا حرف '+getLetterName(ch)+'، ابحث عن '+getLetterName(huntTarget);gentleTrySound();setTimeout(()=>el.remove(),450)}}
function finishLetterHunt(){stopLetterHunt();gamePrompt.textContent='انتهى الوقت — نتيجتك '+huntScoreValue+' نقطة';if(huntScoreValue>=40){setProgress(68,3,'رائع! أنجزت لعبة صيد الحروف.');successSound()}else{gentleTrySound()}newMatchGame()}
function stopLetterHunt(){huntRunning=false;clearInterval(huntTimer);clearInterval(huntSpawn)}
let matchItems=[];
function newMatchGame(){const pool=[...letterData].sort(()=>Math.random()-.5).slice(0,4);matchItems=pool;const left=pool.map(x=>`<div class="drag-card" draggable="true" data-char="${x[0]}">${x[0]}</div>`).join('');const right=[...pool].sort(()=>Math.random()-.5).map(x=>`<div class="drop-card" data-char="${x[0]}">${x[1]}</div>`).join('');matchGame.innerHTML=`<div class="list">${left}</div><div class="list">${right}</div>`;matchGame.querySelectorAll('.drag-card').forEach(el=>{el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.char));el.addEventListener('click',()=>{matchGame.dataset.selected=el.dataset.char;matchGame.querySelectorAll('.drag-card').forEach(x=>x.classList.remove('active'));el.classList.add('active')})});matchGame.querySelectorAll('.drop-card').forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();matchDrop(el,e.dataTransfer.getData('text/plain'))});el.addEventListener('click',()=>matchDrop(el,matchGame.dataset.selected||''))})}
function matchDrop(drop,ch){if(!ch)return;if(drop.dataset.char===ch){drop.classList.add('matched');drop.textContent+=' ✓';const card=[...matchGame.querySelectorAll('.drag-card')].find(x=>x.dataset.char===ch);if(card){card.style.visibility='hidden'}successSound();if(matchGame.querySelectorAll('.drop-card.matched').length===matchItems.length){gameMsg.textContent='أحسنت! أكملت المطابقة كلها.';setProgress(72,3,'أكملت لعبة المطابقة بنجاح!')}}else{gentleTrySound();gameMsg.textContent='حاول مطابقة الحرف باسمه الصحيح.'}}
newMatchGame();

// Enterprise V1.3 Day 3 - Game Studio
const GAME_KEY='iqraGameStudioV13';
let gameState={stars:0,completed:[],bestHunt:0,bestBalloon:0};
try{gameState={...gameState,...JSON.parse(localStorage.getItem(GAME_KEY)||'{}')}}catch(e){}
function saveGameState(){localStorage.setItem(GAME_KEY,JSON.stringify(gameState));renderGameStats()}
function renderGameStats(){if(document.getElementById('gamesStars'))gamesStars.textContent=gameState.stars+' ⭐';if(document.getElementById('gamesCompleted'))gamesCompleted.textContent=gameState.completed.length+' / 5';if(document.getElementById('bestHunt'))bestHunt.textContent=gameState.bestHunt||0;if(document.getElementById('bestBalloon'))bestBalloon.textContent=gameState.bestBalloon||0}
function completeGame(name,stars=2,msg='أحسنت! أكملت اللعبة بنجاح.'){if(!gameState.completed.includes(name))gameState.completed.push(name);gameState.stars+=stars;saveGameState();setProgress(Math.min(84,68+gameState.completed.length*3),3,msg);showGuide(msg);sparkles();successSound()}
function showGamePanel(id,btn){document.querySelectorAll('.game-panel').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('#gameTabs button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active')}
const oldFinishLetterHunt=finishLetterHunt;finishLetterHunt=function(){const score=huntScoreValue;oldFinishLetterHunt();gameState.bestHunt=Math.max(gameState.bestHunt,score);if(score>=40)completeGame('hunt',3,'رائع! أتممت لعبة صيد الحروف.');else saveGameState()}
let balloonTarget='ا',balloonRunning=false,balloonScoreValue=0,balloonRemaining=30,balloonTimer=null,balloonSpawn=null;
function chooseBalloonTarget(){balloonTarget=letters[Math.floor(Math.random()*letters.length)];balloonPrompt.textContent='فرقّع حرف «'+balloonTarget+'» — '+getLetterName(balloonTarget);speakText(getLetterName(balloonTarget))}
function repeatBalloonSound(){speakText(getLetterName(balloonTarget))}
function startBalloonGame(){stopBalloonGame();balloonRunning=true;balloonScoreValue=0;balloonRemaining=30;balloonScore.textContent='0';balloonTime.textContent='30';balloonField.innerHTML='';balloonMsg.textContent='';chooseBalloonTarget();balloonTimer=setInterval(()=>{balloonRemaining--;balloonTime.textContent=balloonRemaining;if(balloonRemaining<=0)finishBalloonGame()},1000);balloonSpawn=setInterval(spawnBalloon,760);for(let i=0;i<5;i++)setTimeout(spawnBalloon,i*160)}
function spawnBalloon(){if(!balloonRunning)return;const el=document.createElement('button');const ch=Math.random()<.34?balloonTarget:letters[Math.floor(Math.random()*letters.length)];el.className='balloon';el.textContent=ch;el.style.right=(3+Math.random()*87)+'%';el.style.animationDuration=(4+Math.random()*2.2)+'s';el.onclick=()=>hitBalloon(el,ch);el.addEventListener('animationend',()=>el.remove());balloonField.appendChild(el)}
function hitBalloon(el,ch){if(!balloonRunning)return;if(ch===balloonTarget){balloonScoreValue+=10;balloonScore.textContent=balloonScoreValue;el.classList.add('pop');balloonMsg.textContent='أحسنت! هذا هو الحرف الصحيح.';successSound();sparkles();setTimeout(()=>el.remove(),300);if(balloonScoreValue%30===0)chooseBalloonTarget()}else{balloonScoreValue=Math.max(0,balloonScoreValue-2);balloonScore.textContent=balloonScoreValue;balloonMsg.textContent='هذا حرف '+getLetterName(ch)+'، حاول مرة أخرى.';gentleTrySound();el.classList.add('bad');setTimeout(()=>el.remove(),350)}}
function stopBalloonGame(){balloonRunning=false;clearInterval(balloonTimer);clearInterval(balloonSpawn)}
function finishBalloonGame(){stopBalloonGame();balloonPrompt.textContent='انتهى الوقت — نتيجتك '+balloonScoreValue+' نقطة';gameState.bestBalloon=Math.max(gameState.bestBalloon,balloonScoreValue);if(balloonScoreValue>=40)completeGame('balloon',3,'ممتاز! أتممت لعبة فرقعة البالونات.');else saveGameState()}
let soundTarget='ا';function playSoundTarget(){speakText(getLetterName(soundTarget))}
function newSoundRound(){const pool=[...letters].sort(()=>Math.random()-.5).slice(0,4);soundTarget=pool[Math.floor(Math.random()*pool.length)];soundChoices.innerHTML=pool.map(ch=>`<button class="choice-card" onclick="answerSoundChoice(this,'${ch}')">${ch}</button>`).join('');soundMsg.textContent='';soundPrompt.textContent='استمع ثم اختر الحرف الصحيح';setTimeout(playSoundTarget,180)}
function answerSoundChoice(el,ch){if(ch===soundTarget){el.classList.add('ok');soundMsg.textContent='إجابة صحيحة: '+getLetterName(ch);completeGame('sound',2,'أحسنت! طابقت الصوت بالحرف الصحيح.')}else{el.classList.add('bad');soundMsg.textContent='حاول مرة أخرى، واستمع جيدًا.';gentleTrySound()}}
let memoryFirst=null,memoryLock=false,memoryPairs=0,memoryMoveCount=0;
function newMemoryGame(){const pool=[...letterData].sort(()=>Math.random()-.5).slice(0,4);const cards=[];pool.forEach(([ch,name],i)=>{cards.push({pair:i,text:ch,type:'char'},{pair:i,text:name,type:'name'})});cards.sort(()=>Math.random()-.5);memoryFirst=null;memoryLock=false;memoryPairs=0;memoryMoveCount=0;memoryMoves.textContent='0';memoryMsg.textContent='';memoryGrid.innerHTML=cards.map((c,i)=>`<button class="memory-card" data-pair="${c.pair}" data-text="${c.text}" onclick="flipMemory(this)">★</button>`).join('')}
function flipMemory(card){if(memoryLock||card.classList.contains('matched')||card===memoryFirst)return;card.classList.add('revealed');card.textContent=card.dataset.text;if(!memoryFirst){memoryFirst=card;return}memoryMoveCount++;memoryMoves.textContent=memoryMoveCount;if(memoryFirst.dataset.pair===card.dataset.pair){memoryFirst.classList.add('matched');card.classList.add('matched');memoryFirst=null;memoryPairs++;successSound();if(memoryPairs===4){memoryMsg.textContent='أحسنت! أكملت لعبة الذاكرة.';completeGame('memory',3,'ذاكرتك رائعة! أتممت جميع الأزواج.')}}else{memoryLock=true;gentleTrySound();setTimeout(()=>{[memoryFirst,card].forEach(x=>{x.classList.remove('revealed');x.textContent='★'});memoryFirst=null;memoryLock=false},850)}}
const wordRounds=[['باب','كوّن كلمة: باب'],['تاج','كوّن كلمة: تاج'],['نور','كوّن كلمة: نور'],['قلم','كوّن كلمة: قلم'],['كتاب','كوّن كلمة: كتاب']];let currentWord='',wordPicked=[];
function newWordGame(){const r=wordRounds[Math.floor(Math.random()*wordRounds.length)];currentWord=r[0];wordPicked=[];wordHint.textContent=r[1];wordSlots.innerHTML=[...currentWord].map(()=>'<div class="word-slot"></div>').join('');const mixed=[...currentWord].sort(()=>Math.random()-.5);wordBank.innerHTML=mixed.map((ch,i)=>`<button class="word-letter" data-i="${i}" onclick="pickWordLetter(this,'${ch}')">${ch}</button>`).join('');wordMsg.textContent=''}
function pickWordLetter(btn,ch){if(btn.disabled)return;wordPicked.push(ch);btn.disabled=true;btn.style.opacity=.35;const slots=[...wordSlots.children];slots[wordPicked.length-1].textContent=ch;if(wordPicked.length===currentWord.length){const made=wordPicked.join('');if(made===currentWord){wordMsg.textContent='أحسنت! كوّنت الكلمة صحيحة.';completeGame('word',3,'رائع! كوّنت الكلمة بنجاح.')}else{wordMsg.textContent='الترتيب غير صحيح، حاول مرة أخرى.';gentleTrySound();setTimeout(clearWordSlots,700)}}}
function clearWordSlots(){wordPicked=[];[...wordSlots.children].forEach(x=>x.textContent='');[...wordBank.children].forEach(x=>{x.disabled=false;x.style.opacity=1});wordMsg.textContent=''}
renderGameStats();newSoundRound();newMemoryGame();newWordGame();

function openGift(){let gifts=['وسام القارئ المجتهد 🏅','نجمتان إضافيتان ⭐⭐','وسام إتقان الحروف 🔤','كأس بطل اليوم 🏆'];giftText.textContent=gifts[Math.floor(Math.random()*gifts.length)];giftModal.classList.add('show');encourage('مبارك! حصلت على مكافأة جديدة.');setProgress(74,3,'رائع! تقدمت خطوة جديدة نحو الشهادة.')} function closeGift(){giftModal.classList.remove('show')}
let mediaRecorder,chunks=[],sec=0,int; startRec.onclick=async()=>{try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}); mediaRecorder=new MediaRecorder(stream); chunks=[]; mediaRecorder.ondataavailable=e=>chunks.push(e.data); mediaRecorder.onstop=()=>{let blob=new Blob(chunks,{type:'audio/webm'}); playback.src=URL.createObjectURL(blob); playback.style.display='block'; sendRec.disabled=false; stream.getTracks().forEach(t=>t.stop())}; mediaRecorder.start(); startRec.disabled=true; stopRec.disabled=false; recState.textContent='جاري التسجيل'; sec=0; int=setInterval(()=>{sec++; timer.textContent='00:'+String(sec).padStart(2,'0'); meter.style.width=(sec%10)*10+'%'},1000)}catch(e){alert('لم يسمح المتصفح باستخدام الميكروفون')}}; stopRec.onclick=()=>{mediaRecorder?.stop();clearInterval(int);startRec.disabled=false;stopRec.disabled=true;recState.textContent='تم التسجيل'}; sendRec.onclick=()=>{recState.textContent='تم الإرسال للمعلمة';teacherRec.textContent=Number(teacherRec.textContent)+1;setProgress(76,3,'تم إرسال تسجيلك للمعلمة. أحسنت!');alert('تم إرسال التسجيل للمعلمة بنجاح')};
teacherList.innerHTML=['سارة','عبدالله','مريم','يوسف'].map((n,i)=>`<div class="item"><span>${n}<br><small class="muted">آيات اليوم والتسجيلات</small></span><span><button class="btn" onclick="alert('تشغيل تسجيل ${n} التجريبي')">استماع</button> <button class="btn gold" onclick="alert('تم اعتماد تسميع ${n}')">اعتماد</button></span></div>`).join('');

function makeCertId(){const d=new Date();return 'IQRA-'+d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+'-'+Math.random().toString(36).slice(2,8).toUpperCase()}
function setDefaultCertDate(){const el=document.getElementById('certDate');if(el&&!el.value)el.value=new Date().toISOString().slice(0,10);const id=document.getElementById('certId');if(id&&!id.value)id.value=makeCertId()}
function issueCertificate(){setDefaultCertDate();if(!certApproved.checked){certStatus.textContent='يرجى اعتماد إكمال المتطلبات أولًا.';certStatus.style.color='#b33';return}outName.textContent=certName.value.trim()||'اسم الطفل/ـة';outCenter.textContent=certCenter.value.trim()||'اسم المركز';outTeacher.textContent=certTeacher.value.trim()||'اسم المعلمة';outLevel.textContent=certLevel.value;outId.textContent=certId.value;outDate.textContent=certDate.value;approvalBadge.textContent='تم الاعتماد';certStatus.textContent='تم إصدار الشهادة بنجاح، ويمكن طباعتها أو حفظها PDF.';certStatus.style.color='var(--green)';const verify='https://iqra-wataallam.local/verify?id='+encodeURIComponent(certId.value);certQr.src='https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(verify);localStorage.setItem('iqraCertificate',JSON.stringify({name:certName.value,center:certCenter.value,teacher:certTeacher.value,level:certLevel.value,date:certDate.value,id:certId.value}));const c=document.getElementById('issuedCount');if(c)c.textContent=Number(c.textContent)+1;setProgress(100,5,'مبارك! اكتملت رحلتك وأصبحت شهادتك جاهزة.')}
certApproved?.addEventListener('change',()=>approvalBadge.textContent=certApproved.checked?'جاهز للإصدار':'بانتظار الاعتماد');setDefaultCertDate();
const saved=localStorage.getItem('iqraCertificate');if(saved){try{const x=JSON.parse(saved);certName.value=x.name||'';certCenter.value=x.center||'';certTeacher.value=x.teacher||'';certLevel.value=x.level||'المستوى الذهبي';certDate.value=x.date||'';certId.value=x.id||makeCertId()}catch(e){}}

if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}

document.getElementById('restartModal')?.addEventListener('click',e=>{if(e.target.id==='restartModal')closeRestartModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRestartModal()});
